---
title: "Idspline tests 1"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# library(dspline)
devtools::load_all()
source("funs.R")
```

Divided differences

```{r}
m = 5
f = rnorm(m)
z = rnorm(m)

max(abs(divided_diff(f[1], z[1]) - f[1])) 
max(abs(divided_diff(f[1:2], z[1:2]) - (f[1]-f[2])/(z[1]-z[2])))
max(abs(divided_diff(f[1:3], z[1:3]) - ((f[1]-f[2])/(z[1]-z[2]) - (f[2]-f[3])/(z[2]-z[3]))/(z[1]-z[3])))

i = sample(m)
max(abs(divided_diff(f, z) - divided_diff(f[i], z[i])))
max(abs(divided_diff(f, 1:m) - diff(f, diff = m-1) / factorial(m-1)))
```

In-place divided differences

```{r}
m = 5
f = rnorm(m)
z = rnorm(m)
g = f+1e-32
.divided_diff(f, z)

max(abs(f[1] - g[1]))
max(abs(f[2]- (g[1]-g[2])/(z[1]-z[2])))
max(abs(f[3] - ((g[1]-g[2])/(z[1]-z[2]) - (g[2]-g[3])/(z[2]-z[3])) / (z[1]-z[3])))

i = sample(m)
max(abs(f[m] - divided_diff(g[i], z[i])))
```

Not supposed to work

```{r}
m = 5
f = sample(m) # Integer vector!!!
z = rnorm(m)
g = f+1e-32
.divided_diff(f, z)

max(abs(f[1] - g[1]))
max(abs(f[2]- (g[1]-g[2])/(z[1]-z[2])))
max(abs(f[3] - ((g[1]-g[2])/(z[1]-z[2]) - (g[2]-g[3])/(z[2]-z[3])) / (z[1]-z[3])))

i = sample(m)
max(abs(f[m] - divided_diff(g[i], z[i])))
```

Discrete derivatives

```{r}
n = 10
k = 2
f = function(x) sin(x)
xd = sort(runif(n))
x = c(0, 0.5, 0.7, 1.1)
d1 = discrete_deriv(f, k, xd, x)

d2 = c()
for (x0 in x) {
  suppressWarnings({i = max(max(which(xd < x0)), 0)})
  kk = min(k, i)
  xx = c(xd[Seq(i-kk+1, i)], x0)
  if (kk == 0) d2 = c(d2, f(x0))
  else d2 = c(d2, getD(kk+1, kk, xx) %*% sapply(xx, f))
}
max(abs(d1 - d2))

f1 = sapply(xd, f)
max(abs(discrete_deriv(f, k, xd, xd) - getB(n, k, xd) %*% f1))
```

Discrete integrals

```{r}
n = 10
k = 2
f = function(x) sin(x)
xd = sort(runif(n))
x = c(xd, 1.1)
f1 = sapply(x, f)
Df = discrete_deriv(c(f1[1:n], f1), k, xd, x)
f2 = discrete_integ(c(Df[1:n], Df), k, xd, x)
max(abs(f1 - f2))
```

Construct D, B matrices

```{r}
n = 10
k = 2
xd = sort(runif(n))
row_idx = sample(n-k, 4)
D1 = d_mat(k, xd, row_idx = row_idx)
D2 = getD(n, k, xd)[row_idx, ]
max(abs(D1 - D2))

n = 10
k = 2
xd = sort(runif(n))
row_idx = sample(n-k, 4)
D1 = d_mat(k, xd, tf_weight = TRUE, row_idx = row_idx)
D2 = getDtil(n, k, xd)[row_idx, ]
max(abs(D1 - D2))

n = 10
k = 2
xd = sort(runif(n))
row_idx = sample(n, 4)
B1 = b_mat(k, xd, row_idx = row_idx)
B2 = getB(n, k, xd)[row_idx, ]
max(abs(B1 - B2))

n = 10
k = 2
xd = sort(runif(n))
row_idx = sample(n, 4)
B1 = b_mat(k, xd, tf_weight = TRUE, row_idx = row_idx)
B2 = getBtil(n, k, xd)[row_idx, ]
max(abs(B1 - B2))
```

Construct H matrix

```{r}
n = 10
k = 2
col_idx = sample(n, 4)
xd = sort(runif(n))
H1 = h_mat(k, xd, col_idx = col_idx)
H2 = getH(n, k, xd)[, col_idx]
max(abs(H1 - H2))

n = 10
k = 2
xd = sort(runif(n))
H = h_mat(k, xd, di_weight = TRUE)
B = b_mat(k+1, xd)
max(abs(H %*% B - diag(n)))
```

Multiply by D matrix

```{r}
n = 10
k = 2
xd = sort(runif(n))
v = rnorm(n)
a1 = d_mat(k, xd) %*% v 
a2 = d_mat_mult(v, k, xd)
max(abs(a1 - a2))

a1 = t(d_mat(k, xd)) %*% v[1:(n-k)]
a2 = d_mat_mult(v[1:(n-k)], k, xd, transpose = TRUE)
max(abs(a1 - a2))

a1 = d_mat(k, xd, tf_weight = TRUE) %*% v
a2 = d_mat_mult(v, k, xd, tf_weight = TRUE)
max(abs(a1 - a2))

a1 = t(d_mat(k, xd, tf_weight = TRUE)) %*% v[1:(n-k)]
a2 = d_mat_mult(v[1:(n-k)], k, xd, tf_weight = TRUE, transpose = TRUE)
max(abs(a1 - a2))
```

Multiply by B matrix

```{r}
n = 10
k = 2
xd = sort(runif(n))
v = rnorm(n)
a1 = b_mat(k, xd) %*% v 
a2 = b_mat_mult(v, k, xd)
max(abs(a1 - a2))

a1 = t(b_mat(k, xd)) %*% v
a2 = b_mat_mult(v, k, xd, transpose = TRUE)
max(abs(a1 - a2))

a1 = solve(b_mat(k, xd), v)
a2 = b_mat_mult(v, k, xd, inverse = TRUE)
max(abs(a1 - a2))

a1 = solve(t(b_mat(k, xd)), v)
a2 = b_mat_mult(v, k, xd, transpose = TRUE, inverse = TRUE)
max(abs(a1 - a2))

a1 = b_mat(k, xd, tf_weight = TRUE) %*% v
a2 = b_mat_mult(v, k, xd, tf_weight = TRUE)
max(abs(a1 - a2))

a1 = t(b_mat(k, xd, tf_weight = TRUE)) %*% v
a2 = b_mat_mult(v, k, xd, tf_weight = TRUE, transpose = TRUE)
max(abs(a1 - a2))

a1 = solve(b_mat(k, xd, tf_weight = TRUE), v)
a2 = b_mat_mult(v, k, xd, tf_weight = TRUE, inverse = TRUE)
max(abs(a1 - a2))

a1 = solve(t(b_mat(k, xd, tf_weight = TRUE)), v)
a2 = b_mat_mult(v, k, xd, tf_weight = TRUE, transpose = TRUE, inverse = TRUE)
max(abs(a1 - a2))
```

Multiply by H matrix

```{r}
n = 10
k = 2
xd = sort(runif(n))
v = rnorm(n)
a1 = h_mat(k, xd) %*% v
a2 = h_mat_mult(v, k, xd)
max(abs(a1 - a2))

a1 = t(h_mat(k, xd)) %*% v
a2 = h_mat_mult(v, k, xd, transpose = TRUE)
max(abs(a1 - a2))

a1 = solve(h_mat(k, xd), v)
a2 = h_mat_mult(v, k, xd, inverse = TRUE)
max(abs(a1 - a2))

a1 = solve(t(h_mat(k, xd)), v)
a2 = h_mat_mult(v, k, xd, transpose = TRUE, inverse = TRUE)
max(abs(a1 - a2))

a1 = h_mat(k, xd, di_weight = TRUE) %*% v
a2 = h_mat_mult(v, k, xd, di_weight = TRUE)
max(abs(a1 - a2))

a1 = t(h_mat(k, xd, di_weight = TRUE)) %*% v
a2 = h_mat_mult(v, k, xd, di_weight = TRUE, transpose = TRUE)
max(abs(a1 - a2))

a1 = solve(h_mat(k, xd, di_weight = TRUE), v)
a2 = h_mat_mult(v, k, xd, di_weight = TRUE, inverse = TRUE)
max(abs(a1 - a2))

a1 = solve(t(h_mat(k, xd, di_weight = TRUE)), v)
a2 = h_mat_mult(v, k, xd, di_weight = TRUE, transpose = TRUE, inverse = TRUE)
max(abs(a1 - a2))
```

Interpolation

```{r}
n = 10
k = 2
xd = sort(runif(n))
x = seq(0, 1, length=100)
v = xd^2 + 0.05 * rnorm(n)
y1 = dspline_interp(v, k, xd, x, implicit = TRUE)
y2 = dspline_interp(v, k, xd, x, implicit = FALSE)
y3 = as.numeric(predict.tf.fitted(x, v, xd, k))
max(abs(y1 - y2))
max(abs(y2 - y3))
```

Newton interpolation

```{r}
k = 4
n = k+1
xd = sort(runif(n))
v = xd^k
x = seq(0, 1, length=100)
y1 = dspline_interp(v, k, xd, x, implicit = TRUE)
y2 = dspline_interp(v, k, xd, x, implicit = FALSE)
y3 = newton_interp(v, xd, x)
max(abs(y1 - y2))
max(abs(y2 - y3))

plot(xd, v)
lines(x, y1)
lines(x, y2, col=2)
```

Construct N matrix 

```{r}
n = 100
k = 2
knot_idx = sort(sample((k+1):(n-1), 4))
xd = sort(runif(n))
N1 = n_mat(k, xd, normalized = FALSE, knot_idx = knot_idx)
N2 = dbs.evals.sk(k, xd, knot_idx)
max(abs(N1 - N2))

# apply(abs(N1 - N2), 2, max)
# matplot(xd, N1, type = "o", lty = 1, pch = 20)
# matplot(xd, N2, type = "o", lty = 1, pch = 20)

H = h_mat(k, xd, col_idx = knot_idx+1)
max(abs(qr.resid(qr(N1), H)))
max(abs(qr.resid(qr(N2), H)))

N1 = n_mat(k, xd, knot_idx = knot_idx)
matplot(xd, N1, type = "o", lty = 1, pch = 20)
```

```{r}
devtools::load_all()
source("funs.R")
```