# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_dot_divided_diff <- function(f, z) {
    invisible(.Call('_dspline_rcpp_dot_divided_diff', PACKAGE = 'dspline', f, z))
}

rcpp_divided_diff <- function(f, z) {
    .Call('_dspline_rcpp_divided_diff', PACKAGE = 'dspline', f, z)
}

rcpp_discrete_deriv <- function(f, k, xd, x) {
    .Call('_dspline_rcpp_discrete_deriv', PACKAGE = 'dspline', f, k, xd, x)
}

rcpp_discrete_integ <- function(f, k, xd, x) {
    .Call('_dspline_rcpp_discrete_integ', PACKAGE = 'dspline', f, k, xd, x)
}

rcpp_b_mat <- function(k, xd, tf_weighting, row_idx, d_only) {
    .Call('_dspline_rcpp_b_mat', PACKAGE = 'dspline', k, xd, tf_weighting, row_idx, d_only)
}

rcpp_h_mat <- function(k, xd, di_weighting, col_idx) {
    .Call('_dspline_rcpp_h_mat', PACKAGE = 'dspline', k, xd, di_weighting, col_idx)
}

rcpp_hx_mat <- function(k, xd, x, di_weighting, col_idx) {
    .Call('_dspline_rcpp_hx_mat', PACKAGE = 'dspline', k, xd, x, di_weighting, col_idx)
}

rcpp_dot_b_mat_mult <- function(v, k, xd, tf_weighting, transpose, inverse) {
    invisible(.Call('_dspline_rcpp_dot_b_mat_mult', PACKAGE = 'dspline', v, k, xd, tf_weighting, transpose, inverse))
}

rcpp_dot_h_mat_mult <- function(v, k, xd, di_weighting, transpose, inverse) {
    invisible(.Call('_dspline_rcpp_dot_h_mat_mult', PACKAGE = 'dspline', v, k, xd, di_weighting, transpose, inverse))
}

rcpp_d_mat_mult <- function(v, k, xd, tf_weighting, transpose) {
    .Call('_dspline_rcpp_d_mat_mult', PACKAGE = 'dspline', v, k, xd, tf_weighting, transpose)
}

rcpp_b_mat_mult <- function(v, k, xd, tf_weighting, transpose, inverse) {
    .Call('_dspline_rcpp_b_mat_mult', PACKAGE = 'dspline', v, k, xd, tf_weighting, transpose, inverse)
}

rcpp_h_mat_mult <- function(v, k, xd, di_weighting, transpose, inverse) {
    .Call('_dspline_rcpp_h_mat_mult', PACKAGE = 'dspline', v, k, xd, di_weighting, transpose, inverse)
}

