# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hj_fun <- function(k, xd, j, x) {
    .Call('_dspline_rcpp_hj_fun', PACKAGE = 'dspline', k, xd, j, x)
}

rcpp_dot_divided_diff <- function(f, z) {
    invisible(.Call('_dspline_rcpp_dot_divided_diff', PACKAGE = 'dspline', f, z))
}

rcpp_divided_diff <- function(f, z) {
    .Call('_dspline_rcpp_divided_diff', PACKAGE = 'dspline', f, z)
}

rcpp_discrete_deriv <- function(f, k, xd, x) {
    .Call('_dspline_rcpp_discrete_deriv', PACKAGE = 'dspline', f, k, xd, x)
}

rcpp_discrete_integ <- function(f, k, xd, x) {
    .Call('_dspline_rcpp_discrete_integ', PACKAGE = 'dspline', f, k, xd, x)
}

